/*
Cloud Hypervisor API

Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IgvmConfig struct for IgvmConfig
type IgvmConfig struct {
	File          string  `json:"file"`
	Size          *int64  `json:"size,omitempty"`
	Iommu         *bool   `json:"iommu,omitempty"`
	DiscardWrites *bool   `json:"discard_writes,omitempty"`
	PciSegment    *int32  `json:"pci_segment,omitempty"`
	Id            *string `json:"id,omitempty"`
}

// NewIgvmConfig instantiates a new IgvmConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIgvmConfig(file string) *IgvmConfig {
	this := IgvmConfig{}
	this.File = file
	var iommu bool = false
	this.Iommu = &iommu
	var discardWrites bool = false
	this.DiscardWrites = &discardWrites
	return &this
}

// NewIgvmConfigWithDefaults instantiates a new IgvmConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIgvmConfigWithDefaults() *IgvmConfig {
	this := IgvmConfig{}
	var iommu bool = false
	this.Iommu = &iommu
	var discardWrites bool = false
	this.DiscardWrites = &discardWrites
	return &this
}

// GetFile returns the File field value
func (o *IgvmConfig) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *IgvmConfig) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *IgvmConfig) SetFile(v string) {
	o.File = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *IgvmConfig) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgvmConfig) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *IgvmConfig) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *IgvmConfig) SetSize(v int64) {
	o.Size = &v
}

// GetIommu returns the Iommu field value if set, zero value otherwise.
func (o *IgvmConfig) GetIommu() bool {
	if o == nil || o.Iommu == nil {
		var ret bool
		return ret
	}
	return *o.Iommu
}

// GetIommuOk returns a tuple with the Iommu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgvmConfig) GetIommuOk() (*bool, bool) {
	if o == nil || o.Iommu == nil {
		return nil, false
	}
	return o.Iommu, true
}

// HasIommu returns a boolean if a field has been set.
func (o *IgvmConfig) HasIommu() bool {
	if o != nil && o.Iommu != nil {
		return true
	}

	return false
}

// SetIommu gets a reference to the given bool and assigns it to the Iommu field.
func (o *IgvmConfig) SetIommu(v bool) {
	o.Iommu = &v
}

// GetDiscardWrites returns the DiscardWrites field value if set, zero value otherwise.
func (o *IgvmConfig) GetDiscardWrites() bool {
	if o == nil || o.DiscardWrites == nil {
		var ret bool
		return ret
	}
	return *o.DiscardWrites
}

// GetDiscardWritesOk returns a tuple with the DiscardWrites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgvmConfig) GetDiscardWritesOk() (*bool, bool) {
	if o == nil || o.DiscardWrites == nil {
		return nil, false
	}
	return o.DiscardWrites, true
}

// HasDiscardWrites returns a boolean if a field has been set.
func (o *IgvmConfig) HasDiscardWrites() bool {
	if o != nil && o.DiscardWrites != nil {
		return true
	}

	return false
}

// SetDiscardWrites gets a reference to the given bool and assigns it to the DiscardWrites field.
func (o *IgvmConfig) SetDiscardWrites(v bool) {
	o.DiscardWrites = &v
}

// GetPciSegment returns the PciSegment field value if set, zero value otherwise.
func (o *IgvmConfig) GetPciSegment() int32 {
	if o == nil || o.PciSegment == nil {
		var ret int32
		return ret
	}
	return *o.PciSegment
}

// GetPciSegmentOk returns a tuple with the PciSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgvmConfig) GetPciSegmentOk() (*int32, bool) {
	if o == nil || o.PciSegment == nil {
		return nil, false
	}
	return o.PciSegment, true
}

// HasPciSegment returns a boolean if a field has been set.
func (o *IgvmConfig) HasPciSegment() bool {
	if o != nil && o.PciSegment != nil {
		return true
	}

	return false
}

// SetPciSegment gets a reference to the given int32 and assigns it to the PciSegment field.
func (o *IgvmConfig) SetPciSegment(v int32) {
	o.PciSegment = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IgvmConfig) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgvmConfig) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IgvmConfig) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IgvmConfig) SetId(v string) {
	o.Id = &v
}

func (o IgvmConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Iommu != nil {
		toSerialize["iommu"] = o.Iommu
	}
	if o.DiscardWrites != nil {
		toSerialize["discard_writes"] = o.DiscardWrites
	}
	if o.PciSegment != nil {
		toSerialize["pci_segment"] = o.PciSegment
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableIgvmConfig struct {
	value *IgvmConfig
	isSet bool
}

func (v NullableIgvmConfig) Get() *IgvmConfig {
	return v.value
}

func (v *NullableIgvmConfig) Set(val *IgvmConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIgvmConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIgvmConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIgvmConfig(val *IgvmConfig) *NullableIgvmConfig {
	return &NullableIgvmConfig{value: val, isSet: true}
}

func (v NullableIgvmConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIgvmConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
